### ISSUE TITLE
Should we document leaky abstraction with Postgres when renaming source columns?

### ISSUE THREAD

**Issue by gkop** [scenic-views/scenic#238]
Using Postgres 9.6.7, if you rename the source column for a view, the view is updated. When this happens the latest version in db/views/ no longer accurately represents the view, but there's no mechanism to alert the developer that they must manually create a new version. Not sure if there's a practical way that scenic could handle this better (e.g., I'd expect it to dump the new version automatically), but since Postgres is so popular, maybe we should document this behavior so that developers will know that in general they have to manually create a new version when renaming a source column?

**Comment by gkop** [comment]
The practical issue is cognitive dissonance when the content of db/views/ doesn't match the checked in schema. As a matter of tidiness and empathy for other developers, I think it's responsible and polite to ensure that db/views/ does matched the checked-in schema. I found Postgres' behavior magical and surprising, and was further surprised that scenic didn't account for it - that's the cognitive dissonance - is this behavior really happening? surely it's not happening. etc. So really I created this issue to share this knowledge with others to save them time understanding what's going on and let them know everything is working correctly, you just need to manually create the new version yourself :relieved:

**Comment by calebthompson** [comment]
I hear what you're saying. I see two concrete issues we'd be trying to solve:

- A future change to that view will highlight the problem because the generated query for the view will not apply correctly.
- it's responsible and polite to ensure that db/views/ does matched the checked-in schema.

For both, I suppose rather than keeping the view definition that you write we could replace it with Postgres' internal definition (which we also put into db/schema.rb). The downside of that is the loss of the pretty formatting you're doing, which is one of the features we provide: write the nice code you want in a .sql file that'll be syntax highlighted.

There's also a convoluted solution involving hooking into column renaming, detecting all views that depend on the table, parsing the SQL in Ruby, and replacing instances of the old column name with the new. I think that'd be very ugly and I'm against it unless there's a pretty way of doing it I'm unaware of.

@gkop thoughts?

**Comment by gkop** [comment]
Thanks for the response Caleb and calling out the issue with the future changes not applying correctly.

Speaking simply as a user of Scenic, based on my organization's use case: We don't want to give up the pretty formatting - we want all the views in db/views/ to be beautiful. We do not rename columns frequently, so having to manually edit the view is no problem for us. Frankly, if Postgres offered a configuration option to disable the behavior where the view is automatically migrated, we could use that option and depend on our automated tests to remind us to cut a new version of the view with scenic (apparently the behavior is deep in Postgres' design, this hypothetical configuration option would be very convoluted or impossible to implement).

The convoluted solution you propose sounds like it would add a lot of bloat to Scenic to support one particular database, so it's hard to get excited about that.

I am tempted by the idea of hooking into column renaming, detecting all views that depend on the table (is this easy?), and doing _something_ helpful. For example, printing a loud warning message to the console. Or, after successful column renaming migrations when RAILS_ENV=development, invoking Scenic to cut new versions of the view automatically (that would certainly get my attention. It seems dirty though that migrating the db could have a side effect of creating new file(s) in db/migrate).

I don't see a great option unfortunately. I'm grateful you kept this issue open though! I hope it has helped another Scenic user figure out what's going on in this circumstance.

**Comment by derekprior** [comment]
> I am tempted by the idea of hooking into column renaming, detecting all views that depend on the table (is this easy?), and doing _something_ helpful.

It's not hard to monkey patch methods and this very gem is built on one. There's no other way to extend schema statements. However, I think hooking `rename_column` and `change_table` would be inviting lots of conflicts as rails changes those things.

I think the best thing we can do is to hope that the generated diff in `schema.rb` or `structure.sql` will be enough to highlight the potential problem.

I'm going to close this for now. I'm not really sure where to document this. If it could be concisely explained, it could go into the README FAQ, but I'm not sure that's going to be very discoverable. It's the kind of thing documentation won't really help us overcome because people that run into this issue won't look at our docs for an answer because it's not like one of our methods they're calling isn't working. 

But maybe they'll search and find this issue...

**Comment by gkop** [comment]
Hope you all are well! Just wanted to add a neat link to a recent mailing list discussion that touches on this consequence of Postgres' behavior: https://www.postgresql.org/message-id/284500.1610120473%40sss.pgh.pa.us . It's cool that Tom uses the same example that I ran into, renaming a column. The search_path issue he mentions is also good for us to be aware of.
