### ISSUE TITLE
Is there a way to turn off pluralization of the view name?

### ISSUE THREAD

**Issue by MadBomber** [scenic-views/scenic#312]
I'm testing scenic to see how it scratches my itch.  The first unexpected thing I found is that when I give the scenicview the name of the view I want it tells me no you don't want that view name you want one that is pluralized.  My standard naming convention is that the view name ends like "*_view" not as scenic demands *_views

Have you got an option in the generator to turn off pluralization?

If not, when I bypass the generator and create my own sql and migration files will scenic play nice with *_view named views?

**Comment by MadBomber** [comment]
Bypassing the generator and using my own naming convention does not seem to be a problem.

The primary benefit to me is keeping a record of the changes to the view configuration over time and the ability to rollback should the need arise.

**Comment by derekprior** [comment]
We pluralize similar to rails models/migrations. In fact, under the covers we rely on some of the same generators.

**Comment by flanger001** [comment]
Apologies for necro-posting here but this issue seemed like the most correct place to put this:

I have an app that has `config.active_record.pluralize_table_names = false` in `application.rb` and I feel like the least-surprise behavior would be that Scenic would respect that setting, but as of version 1.9, it does not:

```shell
$ ./bin/rails g scenic:view foo
      create  db/views/foos_v01.sql
      create  db/migrate/20260311211130_create_foos.rb
```

`config.active_record.pluralize_table_names` has been around since the early days of Rails, so there is some precedent here. Would you accept a PR for this?

**Comment by derekprior** [comment]
@flanger001 Yes, probably. So long as it plays well with the rest of the generators.

**Comment by flanger001** [comment]
@derekprior Once again, apologies for the necro-post but what do you think of the PR I opened about this?

**Comment by flanger001** [comment]
All right. @calebhearth maybe I can get your eyes on this?
