### ISSUE TITLE
Does scenic support redshift database?

### ISSUE THREAD

**Issue by amalkumars** [scenic-views/scenic#335]

**Comment by calebthompson** [comment]
As far as I know, no one has made an adapter for redshift, no.

**Comment by leonid-shevtsov** [comment]
Just for clarity - although Redshift is similar to Postgres - it is not entirely the same, especially when it comes to system tables. For example, the [query to get views from Postgres](https://github.com/scenic-views/scenic/blob/be0980db1023feca2da17a55a68ff0fcad8bf2e6/lib/scenic/adapters/postgres/views.rb#L26) will not work on Redshift, because there's no `pg_extension` catalog.

Additionally, Redshift has features for materialized views that Postgres doesn't - like distkey and sortkey, or auto refresh. They are quite important to specify in the `CREATE` command to create proper Redshift MVs.

So, the PG adapter won't work for Redshift. (And there's still no redshift adapter in February 2023.)

**Comment by calebhearth** [comment]
We maintain the Postgres adapter, but not any others. If a redshift adapter has been written we’re happy to link to it from the README.On Feb 12, 2023, at 11:39 PM, Leonid Shevtsov ***@***.***> wrote:﻿
Just for clarity - although Redshift is similar to Postgres - it is not entirely the same, especially when it comes to system tables. For example, the query to get views from Postgres will not work on Redshift, because there's no pg_extension catalog.
Additionally, Redshift has features for materialized views that Postgres doesn't - like distkey and sortkey, or auto refresh. They are quite important to specify in the CREATE command to create proper Redshift MVs.
So, the PG adapter won't work for Redshift. (And there's still no redshift adapter in February 2023.)
